name: Run the Julia Package Butler

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */1 * * *'

jobs:
  butler:
    name: "Run Package Butler"
    runs-on: ubuntu-latest
    steps:
    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: davidanthoff/julia-pkgbutler@releases/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ssh-private-key: ${{ secrets.JLPKGBUTLER_TOKEN }}
          channel: stable
